# Generated by Django 5.2.3 on 2026-05-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(max_length=100)),
                ('tractor_number', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('cargo_type', models.CharField(choices=[('general', 'General'), ('refrigerated', 'Refrigerated'), ('oversized', 'Oversized'), ('livestock', 'Livestock'), ('hazmat', 'Hazmat')], max_length=50)),
                ('shipper_name', models.CharField(max_length=255)),
                ('load_number', models.CharField(max_length=100)),
                ('hos_cycle', models.CharField(choices=[('70/8', '70 Hours / 8 Days'), ('60/7', '60 Hours / 7 Days')], default='70/8', max_length=10)),
                ('current_cycle_used', models.FloatField(default=0)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('route_instructions', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trips', to=settings.AUTH_USER_MODEL)),
                ('co_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
