# Generated by Django 5.2.3 on 2026-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
